Import Libraries

In [2]:
import pandas as pd
import numpy as np
import sklearn

About Data

In [3]:
from sklearn.datasets import load_iris
iris_dataset = load_iris()

In [8]:
print("Keys of dataset: {}".format(iris_dataset.keys()))

Keys of dataset: dict_keys(['data', 'target', 'target_names', 'DESCR', 'feature_names', 'filename'])


In [9]:
print(iris_dataset['DESCR'][:200])

.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

    :Number of Instances: 150 (50 in each of three classes)
    :Number of Attributes: 4 numeric, predictive


In [10]:
print("Target Names: {}".format(iris_dataset['target_names']))

Target Names: ['setosa' 'versicolor' 'virginica']


In [11]:
print("Feature Names: {}".format(iris_dataset['feature_names']))

Feature Names: ['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']


In [12]:
print("Type of Data: {}".format(type(iris_dataset['data'])))

Type of Data: <class 'numpy.ndarray'>


In [13]:
print("Shape of Data: {}".format(iris_dataset['data'].shape))

Shape of Data: (150, 4)


In [15]:
print("Starting rows of Data: {}".format(iris_dataset['data'][:5]))

Starting rows of Data: [[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]


In [16]:
print("Type of Target: {}".format(type(iris_dataset['target'])))

Type of Target: <class 'numpy.ndarray'>


In [17]:
print("Shape of Target: {}".format(iris_dataset['target'].shape))

Shape of Target: (150,)


In [18]:
print("Target: {}".format(iris_dataset['target']))

Target: [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]


Model Creation, Train and test the data

In [22]:
import sklearn
from sklearn.model_selection import train_test_split

In [24]:
x_train, x_test, y_train, y_test = train_test_split(iris_dataset['data'], iris_dataset['target'], random_state = 0)

In [25]:
print("x_train shape: {}".format(x_train.shape))
print("y_train shape: {}".format(y_train.shape))
print("x_test shape: {}".format(x_test.shape))
print("x_test shape: {}".format(x_test.shape))

x_train shape: (112, 4)
y_train shape: (112,)
x_test shape: (38, 4)
x_test shape: (38, 4)


Solve using K Nearest Neighbor

In [27]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors = 1)

In [28]:
knn.fit(x_train, y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=1, p=2,
                     weights='uniform')

In [ ]:
x_new = np.array([[5, 2.9, 1, 2.0]])
print("Shape of x_new: {}".format(x_new.shape))

It's prediction time

In [36]:
prediction = knn.predict(x_new)
print("Prediction: {}".format(prediction))
print("Target name predicted by model: {}".format(iris_dataset['target_names'][prediction])) 

Prediction: [0]
Target name predicted by model: ['setosa']


In [37]:
y_pred = knn.predict(x_test)
print("Prediction from test data: {}".format(y_pred))

Prediction from test data: [2 1 0 2 0 2 0 1 1 1 2 1 1 1 1 0 1 1 0 0 2 1 0 0 2 0 0 1 1 0 2 1 0 2 2 1 0
 2]


In [38]:
print("Test set score: {}".format(np.mean(y_pred == y_test)))

Test set score: 0.9736842105263158
